### ISSUE TITLE
Singaporeans love to try different cuisines

### ISSUE THREAD

**Issue by RobertManningSmith** [matt-graham/git-example#14]
Need reference to this claim https://github.com/matt-graham/git-example/commit/f67ed2c6d538622bfd572ba7730005326a811908

**Comment by matt-graham** [comment]
Good point, this is a bit a little bit of an over generalization 😅, perhaps needs some qualification. Can I cite personal experience?

**Comment by RobertManningSmith** [comment]
oof, small sample size. Might not hold up under review but just this onece
